Repository modern-agile-team/dongurami-server-v2, pull requests merged in 2023-11, with the labels that each got.

#10 project set up
  .github/.COMMIT_TEMPLATE.txt
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/general.md
  .github/issue-branch.yml
  .github/labels.json
  .github/pull_request_template.md
  .gitignore
  README.md
  package.json
  scripts/prepare-commit-msg.sh
Labels: Setting, Doc

#11 apply ci/cd
  .dockerignore
  .github/workflows/dongurami-v2.yml
  docker-compose.yml
  dockerfile
  package.json
  src/apis/admin-option/controllers/admin-option.controller.ts
  src/app.module.ts
  src/common/utils/validation.ts
Labels: Setting

#15 develop to main merge
  .github/.COMMIT_TEMPLATE.txt
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/general.md
  .github/issue-branch.yml
  .github/labels.json
  .github/pull_request_template.md
  .github/workflows/create_branch_for_issue.yml
  .gitignore
  README.md
  package.json
  scripts/prepare-commit-msg.sh
Labels: Deploy

#18 custom config module
  package.json
  src/app.module.ts
  src/core/app-config/app-config.module.ts
  src/core/app-config/constants/app-config.constant.ts
  src/core/app-config/services/app-config.service.spec.ts
  src/core/app-config/services/app-config.service.ts
  tsconfig.json
Labels: Setting

#16 entity modeling
  .gitignore
  README.md
  migrations/1700205074777-init.ts
  migrations/1700481633507-init-seed.ts
  output/entities/Club.ts
  output/entities/ClubCategory.ts
  output/entities/ClubJoinApplication.ts
  output/entities/ClubMember.ts
  output/entities/FreeBoard.ts
  output/entities/FreeBoardComment.ts
  output/entities/FreeBoardCommentReaction.ts
  output/entities/FreeBoardReaction.ts
  output/entities/FreeBoardReplyComment.ts
  output/entities/FreeBoardReplyCommentReaction.ts
  output/entities/LoginType.ts
  output/entities/Major.ts
  output/entities/Migrations.ts
  output/entities/ReactionType.ts
  output/entities/User.ts
  output/tsconfig.json
  package-lock.json
  package.json
  typeorm.config.ts
Labels: Setting

#21 apply pr reminder
  .github/CODEOWNERS
  .github/workflows/pr-reminder.yml
Labels: Feat

#25 Stay on the main dev branch
  .github/CODEOWNERS
  .github/workflows/pr-reminder.yml
  .gitignore
  README.md
  migrations/1700205074777-init.ts
  migrations/1700481633507-init-seed.ts
  output/entities/Club.ts
  output/entities/ClubCategory.ts
  output/entities/ClubJoinApplication.ts
  output/entities/ClubMember.ts
  output/entities/FreeBoard.ts
  output/entities/FreeBoardComment.ts
  output/entities/FreeBoardCommentReaction.ts
  output/entities/FreeBoardReaction.ts
  output/entities/FreeBoardReplyComment.ts
  output/entities/FreeBoardReplyCommentReaction.ts
  output/entities/LoginType.ts
  output/entities/Major.ts
  output/entities/Migrations.ts
  output/entities/ReactionType.ts
  output/entities/User.ts
  output/tsconfig.json
  package-lock.json
  package.json
  src/app.module.ts
  src/core/app-config/app-config.module.ts
  src/core/app-config/constants/app-config.constant.ts
  src/core/app-config/services/app-config.service.spec.ts
  src/core/app-config/services/app-config.service.ts
  tsconfig.json
  typeorm.config.ts
Labels: Deploy

#26 create notice board entity
  migrations/1700634679995-notice-board.ts
  output/entities/NoticeBoard.ts
  output/entities/NoticeBoardComment.ts
  output/entities/NoticeBoardCommentReaction.ts
  output/entities/NoticeBoardReaction.ts
  output/entities/NoticeBoardReplyComment.ts
  output/entities/NoticeBoardReplyCommentReaction.ts
  output/entities/ReactionType.ts
  output/entities/User.ts
  package.json
Labels: Setting

#28 set main.js route(ci/cd)
  package.json
Labels: Setting

#29 change secrets name
  .github/workflows/dongurami-v2.yml
Labels: Setting

#30 edit dockerignore, add slack-push-notification(incomplete)
  .dockerignore
  .github/workflows/slack-push-notification.yml
Labels: Setting

#31 setting/#24: modify workflow
  .github/workflows/dongurami-v2.yml
Labels: Setting

#32 modify workflow
  .github/workflows/dongurami-v2.yml
Labels: Setting

#33 setting/#24: modify workflow
  .github/workflows/dongurami-v2.yml
  dockerfile
Labels: Setting

#34 email login api
  package-lock.json
  package.json
  src/apis/auth/auth.module.ts
  src/apis/auth/contollers/auth.controller.spec.ts
  src/apis/auth/contollers/auth.controller.ts
  src/apis/auth/dto/sign-in-request-body.dto.ts
  src/apis/auth/jwt/jwt-module-options.factory.ts
  src/apis/auth/jwt/jwt.guard.ts
  src/apis/auth/jwt/jwt.strategy.ts
  src/apis/auth/services/auth.service.spec.ts
  src/apis/auth/services/auth.service.ts
  src/apis/auth/type/auth.type.ts
  src/apis/users/services/users.service.spec.ts
  src/apis/users/services/users.service.ts
  src/apis/users/users.module.ts
  src/core/app-config/app-config.module.ts
  src/core/app-config/constants/app-config.constant.ts
  src/decorators/user.decorator.ts
  src/libs/encryption/constants/encryption.token.ts
  src/libs/encryption/encryption.module.ts
  src/libs/encryption/services/encryption.service.spec.ts
  src/libs/encryption/services/encryption.service.ts
  src/middlewares/use-development.middleware.ts
  src/pipes/parse-positive-int.pipe.spec.ts
  src/pipes/parse-positive-int.pipe.ts
  test/mock/mock.service.ts
Labels: Feat

#41 logger middleware
  src/app.module.ts
  src/middlewares/logger.middleware.ts
Labels: Feat

#37 success interceptor
  src/apis/auth/contollers/auth.controller.ts
  src/apis/users/controllers/users.controller.ts
  src/app.module.ts
  src/common/common.spec.ts
  src/common/common.ts
  src/constants/constant.ts
  src/dto/page.dto.ts
  src/entities/ReactionType.ts
  src/interceptors/interceptor.module.ts
  src/interceptors/success-interceptor/builders/response.builder.spec.ts
  src/interceptors/success-interceptor/builders/success-response.builder.ts
  src/interceptors/success-interceptor/constants/success-interceptor.constant.ts
  src/interceptors/success-interceptor/constants/success-interceptor.enum.ts
  src/interceptors/success-interceptor/decorators/success-response.decorator.ts
  src/interceptors/success-interceptor/dto/common-response.dto.ts
  src/interceptors/success-interceptor/dto/delete-response.dto.ts
  src/interceptors/success-interceptor/dto/detail-response.dto.ts
  src/interceptors/success-interceptor/dto/pagination-response.dto.ts
  src/interceptors/success-interceptor/success-interceptor.module.ts
  src/interceptors/success-interceptor/success.interceptor.ts
  src/interceptors/success-interceptor/types/success-interceptor.type.ts
  src/main.ts
Labels: Feat

#43 swagger setup
  src/core/app-config/app-config.module.ts
  src/core/app-config/constants/app-config.constant.ts
  src/main.ts
Labels: Feat

#45 error code modeling
  .github/workflows/dongurami-v2.yml
  dockerfile
  src/apis/auth/constants/auth-error-code.constant.ts
  src/apis/auth/constants/auth-error-message.constant.ts
  src/apis/users/constants/user-error-code.constant.ts
  src/apis/users/constants/user-error-message.constant.ts
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.spec.ts
  src/app.service.ts
  src/constants/common-error-code.constant.ts
  src/constants/common-error-message.constant.ts
  src/core/app-config/app-config.module.ts
  src/main.ts
  src/types/type.ts
Labels: Feat

#49 ci/cd notification for slack
  .github/workflows/dongurami-v2.yml
  .github/workflows/slack-push-notification.yml
Labels: Setting

#50 exception filter
  src/apis/auth/jwt/jwt.strategy.ts
  src/apis/auth/services/auth.service.spec.ts
  src/apis/auth/services/auth.service.ts
  src/apis/users/controllers/users.controller.spec.ts
  src/apis/users/services/users.service.spec.ts
  src/apis/users/services/users.service.ts
  src/app.controller.spec.ts
  src/app.module.ts
  src/app.service.ts
  src/constants/error/auth/auth-error-code.constant.ts
  src/constants/error/auth/auth-error-message.constant.ts
  src/constants/error/common/common-error-code.constant.ts
  src/constants/error/common/common-error-message.constant.ts
  src/constants/error/error-code.constant.ts
  src/constants/error/error-message.constant.ts
  src/constants/error/users/user-error-code.constant.ts
  src/constants/error/users/user-error-message.constant.ts
  src/http-exceptions/dto/exception-response.dto.ts
  src/http-exceptions/exceptions/http-bad-request.exception.ts
  src/http-exceptions/exceptions/http-conflict.exception.ts
  src/http-exceptions/exceptions/http-forbidden.exception.ts
  src/http-exceptions/exceptions/http-internal-server-error.exception.ts
  src/http-exceptions/exceptions/http-not-found.exception.ts
  src/http-exceptions/exceptions/http-process-error.exception.ts
  src/http-exceptions/exceptions/http-unauthorized.exception.ts
  src/http-exceptions/exceptions/http.exception.ts
  src/http-exceptions/filters/http-bad-request-exception.filter.ts
  src/http-exceptions/filters/http-conflict-exception.filter.ts
  src/http-exceptions/filters/http-forbidden-exception.filter.ts
  src/http-exceptions/filters/http-internal-server-error-exception.filter.ts
  src/http-exceptions/filters/http-not-found-exception.filter.ts
  src/http-exceptions/filters/http-path-not-found-exception.filter.ts
  src/http-exceptions/filters/http-process-error-exception.filter.ts
  src/http-exceptions/filters/http-remainder-exception.filter.ts
  src/http-exceptions/filters/http-unauthorized-exception.filter.ts
  src/http-exceptions/http-exception.module.ts
  src/http-exceptions/services/http-exception.service.ts
  src/http-exceptions/types/exception.type.ts
  src/interceptors/success-interceptor/builders/response.builder.spec.ts
  src/interceptors/success-interceptor/builders/success-response.builder.ts
  src/main.ts
  src/pipes/parse-positive-int.pipe.spec.ts
  src/pipes/parse-positive-int.pipe.ts
  src/types/type.ts
Labels: Feat

#56 apply logger middleware
  src/app.module.ts
Labels: Feat

#54 free board history entity
  migrations/1701161261517-free-board-history.ts
  src/entities/FreeBoard.ts
  src/entities/FreeBoardCommentHistory.ts
  src/entities/FreeBoardHistory.ts
  src/entities/FreeBoardReplyCommentHistory.ts
  src/entities/User.ts
Labels: Feat

#58 add notification on fail, add channel id
  .github/workflows/dongurami-v2.yml
Labels: Setting

#52 swagger advanced
  src/apis/auth/contollers/auth.controller.ts
  src/apis/auth/contollers/auth.swagger.ts
  src/apis/users/controllers/users.controller.ts
  src/apis/users/controllers/users.swagger.ts
  src/apis/users/dto/create-user-request-body.dto.ts
  src/apis/users/dto/user.dto.ts
  src/app.controller.ts
  src/app.swagger.ts
  src/dto/base.dto.ts
  src/http-exceptions/exceptions/http.exception.ts
  src/interceptors/success-interceptor/dto/common-response.dto.ts
  src/interceptors/success-interceptor/dto/delete-response.dto.ts
  src/interceptors/success-interceptor/dto/detail-response.dto.ts
  src/interceptors/success-interceptor/dto/pagination-response.dto.ts
  src/types/type.ts
  src/types/validation-errors.type.ts
Labels: Feat

#60 match major category
  migrations/1701237915751-major-init-seed.ts
Labels: Setting

#62 modify yml
  .github/workflows/dongurami-v2.yml
Labels: Setting

#65 modify yml
  .github/workflows/dongurami-v2.yml
Labels: Setting

#63 create free board api
  src/apis/api.module.ts
  src/apis/auth/jwt/jwt.guard.ts
  src/apis/free-boards/constants/free-board.constant.ts
  src/apis/free-boards/controllers/free-board.swagger.ts
  src/apis/free-boards/controllers/free-boards.controller.spec.ts
  src/apis/free-boards/controllers/free-boards.controller.ts
  src/apis/free-boards/dto/create-free-board.dto.ts
  src/apis/free-boards/dto/free-board.dto.ts
  src/apis/free-boards/dto/update-free-board.dto.ts
  src/apis/free-boards/free-board-history/dto/create-free-board-history.dto.ts
  src/apis/free-boards/free-board-history/free-board-history.module.ts
  src/apis/free-boards/free-board-history/services/free-board-history.service.spec.ts
  src/apis/free-boards/free-board-history/services/free-board-history.service.ts
  src/apis/free-boards/free-boards.module.ts
  src/apis/free-boards/services/free-board.service.spec.ts
  src/apis/free-boards/services/free-board.service.ts
  src/entities/FreeBoard.ts
  src/entities/FreeBoardHistory.ts
  src/entities/transfomers/boolean.transfomer.ts
  test/mock/mock.repository.ts
  test/mock/mock.service.ts
Labels: Feat
