Repository modern-agile-team/dongurami-server-v2, pull requests merged in 2023-12, with the labels that each got.

#67 자유게시글 전체조회
  src/apis/free-boards/constants/free-board.constant.ts
  src/apis/free-boards/controllers/free-board.swagger.ts
  src/apis/free-boards/controllers/free-boards.controller.spec.ts
  src/apis/free-boards/controllers/free-boards.controller.ts
  src/apis/free-boards/dto/find-free-board-list-query.dto.ts
  src/apis/free-boards/dto/free-boards-item.dto.ts
  src/apis/free-boards/free-boards.module.ts
  src/apis/free-boards/services/free-board.service.spec.ts
  src/apis/free-boards/services/free-board.service.ts
  src/common/common.spec.ts
  src/common/common.ts
  src/constants/enum.ts
  src/dto/swagger/api-property-order.decorator.ts
  src/dto/transformer/csv-to-order.decorator.spec.ts
  src/dto/transformer/csv-to-order.decorator.ts
  src/dto/validator/is-positive-int.decorator.spec.ts
  src/dto/validator/is-positive-int.decorator.ts
  src/helpers/query.helper.spec.ts
  src/helpers/query.helper.ts
  test/mock/mock.helper.ts
  test/mock/mock.service.ts
Labels: Feat

#69 free board 상세조회
  src/apis/free-boards/controllers/free-board.swagger.ts
  src/apis/free-boards/controllers/free-boards.controller.spec.ts
  src/apis/free-boards/controllers/free-boards.controller.ts
  src/apis/free-boards/services/free-board.service.spec.ts
  src/apis/free-boards/services/free-board.service.ts
  test/mock/mock.service.ts
Labels: Feat

#83 free board is anonymous
  migrations/1701691099460-free-board-is-anonymous.ts
  src/entities/FreeBoard.ts
  src/entities/FreeBoardComment.ts
  src/entities/FreeBoardCommentHistory.ts
  src/entities/FreeBoardHistory.ts
  src/entities/FreeBoardReplyComment.ts
  src/entities/FreeBoardReplyCommentHistory.ts
Labels: Modify

#79 user history
  migrations/1701675711005-user-soft-delete.ts
  migrations/1701678486841-user-history.ts
  src/apis/users/constants/user.enum.ts
  src/apis/users/dto/user.dto.ts
  src/apis/users/services/users.service.spec.ts
  src/apis/users/services/users.service.ts
  src/apis/users/user-history/dto/create-user-history.dto.ts
  src/apis/users/user-history/services/user-history.service.spec.ts
  src/apis/users/user-history/services/user-history.service.ts
  src/apis/users/user-history/user-history.module.ts
  src/apis/users/users.module.ts
  src/constants/enum.ts
  src/entities/Major.ts
  src/entities/User.ts
  src/entities/UserHistory.ts
  test/mock/mock.repository.ts
  test/mock/mock.service.ts
Labels: Feat, Modify

#74 create notice board post, getAll apis
  migrations/1700634679995-notice-board.ts
  migrations/1701328900610-notice-board-history.ts
  migrations/1701696068699-notice-board-change-column-name.ts
  migrations/1701700089002-notice-board-soft-delete.ts
  src/apis/api.module.ts
  src/apis/notice-boards/constants/notice-board.constant.ts
  src/apis/notice-boards/constants/notice-board.enum.ts
  src/apis/notice-boards/controllers/notice-boards.controller.ts
  src/apis/notice-boards/controllers/notice-boards.swagger.ts
  src/apis/notice-boards/dto/create-notice-board.dto.ts
  src/apis/notice-boards/dto/find-notice-board-list-query.dto.ts
  src/apis/notice-boards/dto/notice-board.dto.ts
  src/apis/notice-boards/dto/notice-boards-item.dto.ts
  src/apis/notice-boards/notice-board-history/dto/create-notice-board-history.dto.ts
  src/apis/notice-boards/notice-board-history/notice-board-history.module.ts
  src/apis/notice-boards/notice-board-history/services/notice-board-history.service.ts
  src/apis/notice-boards/notice-boards.module.ts
  src/apis/notice-boards/services/notice-boards.service.ts
  src/entities/FreeBoard.ts
  src/entities/NoticeBoard.ts
  src/entities/NoticeBoardComment.ts
  src/entities/NoticeBoardCommentHistory.ts
  src/entities/NoticeBoardCommentReaction.ts
  src/entities/NoticeBoardHistory.ts
  src/entities/NoticeBoardReaction.ts
  src/entities/NoticeBoardReplyComment.ts
  src/entities/NoticeBoardReplyCommentHistory.ts
  src/entities/NoticeBoardReplyCommentReaction.ts
  src/entities/User.ts
  src/entities/transformers/boolean.transformer.ts
Labels: Feat

#90 add user student number
  migrations/1701771662843-add-user-student-number.ts
  src/entities/User.ts
Labels: Feat

#85 typeorm ex module
  src/apis/users/users.module.ts
  src/core/type-orm/constants/type-orm.token.ts
  src/core/type-orm/decorators/custom-repository.decorator.ts
  src/core/type-orm/type-orm-ex.module.ts
Labels: Feat

#75 notice board crud detail
  src/apis/notice-boards/controllers/notice-boards.controller.spec.ts
  src/apis/notice-boards/controllers/notice-boards.controller.ts
  src/apis/notice-boards/controllers/notice-boards.swagger.ts
  src/apis/notice-boards/services/notice-boards.service.spec.ts
  src/apis/notice-boards/services/notice-boards.service.ts
Labels: Feat

#93 delete password regexp pattern at sign in
  src/apis/auth/dto/sign-in-request-body.dto.ts
  src/apis/users/dto/create-user-request-body.dto.ts
Labels: Modify

#95 apply custom repository
  src/apis/free-posts/controllers/free-posts.controller.ts
  src/apis/free-posts/controllers/free-posts.swagger.ts
  src/apis/free-posts/free-post-history/free-post-history.module.ts
  src/apis/free-posts/free-post-history/repositories/free-post-history.repository.ts
  src/apis/free-posts/free-post-history/services/free-post-history.service.spec.ts
  src/apis/free-posts/free-post-history/services/free-post-history.service.ts
  src/apis/free-posts/free-posts.module.ts
  src/apis/free-posts/repositories/free-post.repository.ts
  src/apis/free-posts/services/free-posts.service.spec.ts
  src/apis/free-posts/services/free-posts.service.ts
  src/apis/major/major.module.ts
  src/apis/major/repositories/major.repository.ts
  src/apis/major/services/major.service.ts
  src/apis/notice-posts/notice-post-history/notice-posts-history.module.ts
  src/apis/notice-posts/notice-post-history/repositories/notice-post-history.repository.ts
  src/apis/notice-posts/notice-post-history/services/notice-posts-history.service.ts
  src/apis/notice-posts/notice-posts.module.ts
  src/apis/notice-posts/repositories/notice-post.repository.ts
  src/apis/notice-posts/services/notice-posts.service.ts
  src/apis/users/repositories/user.repository.ts
  src/apis/users/services/users.service.spec.ts
  src/apis/users/services/users.service.ts
  src/apis/users/user-history/repositories/user-history.repository.ts
  src/apis/users/user-history/services/user-history.service.spec.ts
  src/apis/users/user-history/services/user-history.service.ts
  src/apis/users/user-history/user-history.module.ts
  src/apis/users/users.module.ts
  test/mock/mock.repository.ts
Labels: Refactor

#97 free post increase hit
  src/apis/api.module.ts
  src/apis/common-posts/common-posts.module.ts
  src/apis/common-posts/constants/common-posts.enum.ts
  src/apis/common-posts/constants/common-posts.token.ts
  src/apis/common-posts/services/common-posts.service.spec.ts
  src/apis/common-posts/services/common-posts.service.ts
  src/apis/free-posts/controllers/free-posts.controller.spec.ts
  src/apis/free-posts/controllers/free-posts.controller.ts
  src/apis/free-posts/controllers/free-posts.swagger.ts
  src/apis/free-posts/free-posts.module.ts
  src/dto/validator/is-positive-int.decorator.spec.ts
  test/mock/mock.service.ts
Labels: Feat

#98 notice board crud patch
  src/apis/free-posts/controllers/free-posts.swagger.ts
  src/apis/notice-posts/controllers/notice-posts.controller.ts
  src/apis/notice-posts/controllers/notice-posts.swagger.ts
  src/apis/notice-posts/dto/patch-update-notice-post.dto.ts
  src/apis/notice-posts/services/notice-posts.service.ts
Labels: Feat

#99 Feat/#66/notice board crud remove
  src/apis/notice-posts/controllers/notice-posts.controller.ts
  src/apis/notice-posts/controllers/notice-posts.swagger.ts
  src/apis/notice-posts/services/notice-posts.service.ts
Labels: Feat

#101 reaction module
  src/apis/reactions/constants/reaction.enum.ts
  src/apis/reactions/constants/reaction.token.ts
  src/apis/reactions/reactions.module.ts
  src/apis/reactions/repositories/reaction-type.repository.ts
  src/apis/reactions/services/reactions.service.spec.ts
  src/apis/reactions/services/reactions.service.ts
  src/apis/reactions/types/reaction.type.ts
  src/constants/error/error-code.constant.ts
  src/constants/error/error-message.constant.ts
  src/constants/error/reaction/reaction-error-code.constant.ts
  src/constants/error/reaction/reaction-error-message.constant.ts
  src/entities/FreePostReaction.ts
  test/mock/mock.repository.ts
Labels: Feat

#102 refactoring common post module
  src/apis/common-posts/common-posts.module.ts
  src/apis/common-posts/services/common-posts.service.spec.ts
  src/apis/common-posts/services/common-posts.service.ts
  src/apis/common-posts/types/common-post.type.ts
  src/apis/free-posts/controllers/free-posts.controller.spec.ts
  src/apis/free-posts/controllers/free-posts.controller.ts
  src/apis/free-posts/free-posts.module.ts
  src/apis/free-posts/services/free-posts.service.spec.ts
  src/apis/free-posts/services/free-posts.service.ts
  test/mock/mock.service.ts
Labels: Refactor

#103 notice posts crud hit
  migrations/1700634679995-notice-board.ts
  migrations/1701328900610-notice-board-history.ts
  migrations/1701696068699-notice-board-change-column-name.ts
  src/apis/notice-posts/controllers/notice-posts.controller.ts
  src/apis/notice-posts/controllers/notice-posts.swagger.ts
  src/apis/notice-posts/notice-posts.module.ts
  src/apis/notice-posts/services/notice-posts.service.ts
Labels: Feat, Modify

#107 modify pagination response
  src/interceptors/success-interceptor/builders/success-response.builder.ts
  src/interceptors/success-interceptor/dto/pagination-response.dto.ts
Labels: Modify
