Repository modern-agile-team/dongurami-server-v2, pull requests merged in 2024-02, with the labels that each got.

#122 migration file 정리
  migrations/1700205074777-init.ts
  migrations/1700481633507-init-seed.ts
  migrations/1700634679995-notice-board.ts
  migrations/1701161261517-free-board-history.ts
  migrations/1701328900610-notice-board-history.ts
  migrations/1701675711005-user-soft-delete.ts
  migrations/1701684589261-free-board-soft-delete.ts
  migrations/1701691099460-free-board-is-anonymous.ts
  migrations/1701696068699-notice-board-change-column-name.ts
  migrations/1701700089002-notice-board-soft-delete.ts
  migrations/1701757608194-modify-free-board-name.ts
  migrations/1701771662843-add-user-student-number.ts
  migrations/1701922741215-modify-notice-board-name.ts
  migrations/1702292764679-free-comment-soft-delete.ts
  migrations/1704208353171-add-modify-user-table-column.ts
  migrations/1704441168745-add-enum-type-in-loginType.ts
  migrations/__utils/util.ts
  migrations/common/1706439999274-reaction-type.ts
  migrations/free-post/1706440108331-free-post.ts
  migrations/free-post/1706440397286-free-post-history.ts
  migrations/free-post/1706440474169-free-post-reaction.ts
  migrations/free-post/1706440963992-free-post-comment.ts
  migrations/free-post/1706441662158-free-post-comment-history.ts
  migrations/free-post/1706441929477-free-post-comment-reaction.ts
  migrations/free-post/1706442010302-free-post-reply-comment.ts
  migrations/free-post/1706442523748-free-post-reply-comment-reaction.ts
  migrations/free-post/1706442579113-free-post-reply-comment-history.ts
  migrations/notice-post/1706442705381-notice-post.ts
  migrations/notice-post/1706442725957-notice-post-history.ts
  migrations/notice-post/1706442730064-notice-post-reaction.ts
  migrations/notice-post/1706442736320-notice-post-comment.ts
  migrations/notice-post/1706442739850-notice-post-comment-history.ts
  migrations/notice-post/1706442745023-notice-post-comment-reaction.ts
  migrations/notice-post/1706442757008-notice-post-reply-comment.ts
  migrations/notice-post/1706443176569-notice-post-reply-comment-reaction.ts
  migrations/notice-post/1706443180572-notice-post-reply-comment-history.ts
  migrations/user/1706435061683-user-major.ts
  migrations/user/1706436836635-user.ts
  migrations/user/1706437519634-user-history.ts
  src/apis/major/dto/major.dto.ts
  src/apis/major/repositories/major.repository.ts
  src/apis/major/services/major.service.ts
  src/entities/User.ts
  src/entities/UserHistory.ts
  src/entities/UserMajor.ts
  typeorm.config.ts
Labels: DB

#131 QYOG-38 소셜 회원가입 fix (1차)
  migrations/user/1706878330599-user-email-nullable.ts
  package-lock.json
  package.json
  src/apis/auth/dto/sign-in-request-body.dto.ts
  src/apis/auth/social/dto/auth-social.dto.ts
  src/apis/auth/social/service/auth-social.service.ts
  src/apis/users/controllers/users.controller.spec.ts
  src/apis/users/controllers/users.controller.ts
  src/apis/users/dto/create-user.dto.ts
  src/apis/users/dto/put-update-user.dto.ts
  src/apis/users/services/users.service.spec.ts
  src/apis/users/services/users.service.ts
  src/constants/error/users/user-error-code.constant.ts
  src/constants/error/users/user-error-message.constant.ts
  src/entities/User.ts
  src/entities/UserHistory.ts
Labels: Refactor, Feat

#128 operationId Automation
  package-lock.json
  package.json
  src/apis/auth/contollers/auth.swagger.ts
  src/apis/auth/social/controllers/auth-social.swagger.ts
  src/apis/free-post-comments/controllers/free-post-comments.swagger.ts
  src/apis/free-post-reply-comments/controllers/free-post-reply-comments.swagger.ts
  src/apis/free-posts/controllers/free-posts.swagger.ts
  src/apis/major/controllers/major.swagger.ts
  src/apis/notice-posts/controllers/notice-posts.swagger.ts
  src/apis/root/controllers/root.swagger.ts
  src/apis/users/controllers/users.swagger.ts
  src/app.service.ts
Labels: Doc, Auto

#130 api common error code
  src/apis/auth/auth.module.ts
  src/apis/auth/controllers/auth.controller.spec.ts
  src/apis/auth/controllers/auth.controller.ts
  src/apis/auth/controllers/auth.swagger.ts
  src/apis/auth/social/controllers/auth-social.controller.ts
  src/apis/auth/social/controllers/auth-social.swagger.ts
  src/apis/free-post-comments/controllers/free-post-comments.controller.ts
  src/apis/free-post-comments/controllers/free-post-comments.swagger.ts
  src/apis/free-post-reply-comments/controllers/free-post-reply-comments.controller.ts
  src/apis/free-post-reply-comments/controllers/free-post-reply-comments.swagger.ts
  src/apis/free-posts/controllers/free-posts.controller.ts
  src/apis/free-posts/controllers/free-posts.swagger.ts
  src/apis/major/controllers/major.controller.ts
  src/apis/major/controllers/major.swagger.ts
  src/apis/notice-posts/controllers/notice-posts.controller.ts
  src/apis/notice-posts/controllers/notice-posts.swagger.ts
  src/apis/users/controllers/users.controller.ts
  src/apis/users/controllers/users.swagger.ts
  src/decorators/swagger/api-common-response.swagger.ts
Labels: Doc

#133 error시에 log를 filter layer에서 프린트하게 변경
  src/apis/free-post-comments/services/free-post-comments.service.ts
  src/apis/free-post-reply-comments/services/free-post-reply-comments.service.ts
  src/apis/free-posts/services/free-posts.service.ts
  src/apis/notice-posts/services/notice-posts.service.ts
  src/apis/users/services/users.service.ts
  src/http-exceptions/exceptions/http-internal-server-error.exception.ts
  src/http-exceptions/filters/http-internal-server-error-exception.filter.ts
  src/http-exceptions/filters/http-process-error-exception.filter.ts
  src/http-exceptions/filters/http-remainder-exception.filter.ts
  src/http-exceptions/services/http-exception.service.ts
Labels: Refactor

#135 appService bootstrapService로 변경
  src/app.module.ts
  src/bootstrap.service.ts
  src/main.ts
Labels: Refactor

#134 transactional 데코레이터로 transaction 관리하게 변경
  package-lock.json
  package.json
  src/apis/free-post-comments/free-post-comment-history/services/free-post-comment-history.service.ts
  src/apis/free-post-comments/services/free-post-comments.service.ts
  src/apis/free-post-reply-comments/free-post-reply-comment-history/services/free-post-reply-comment-history.service.ts
  src/apis/free-post-reply-comments/services/free-post-reply-comments.service.ts
  src/apis/free-posts/free-post-history/services/free-post-history.service.ts
  src/apis/free-posts/services/free-posts.service.ts
  src/apis/notice-posts/notice-post-history/services/notice-posts-history.service.ts
  src/apis/notice-posts/services/notice-posts.service.ts
  src/apis/users/services/users.service.ts
  src/apis/users/user-history/services/user-history.service.ts
  src/core/core.module.ts
  src/main.ts
Labels: Refactor

#136 post 관련 리소스 변수명 간소화
  src/apis/free-post-comments/controllers/free-post-comments.controller.ts
  src/apis/free-post-reply-comments/controllers/free-post-reply-comments.controller.ts
  src/apis/free-posts/controllers/free-posts.controller.ts
  src/apis/notice-posts/controllers/notice-posts.controller.ts
Labels: Refactor

#138 TypeORM timezone 설정 추가
  src/core/type-orm/type-orm-module-options.factory.ts
  typeorm.config.ts
Labels: setup, DB

#137 audit log typeorm subscriber를 이용하게 변경
  src/apis/free-post-comments/free-post-comment-history/dto/create-free-post-comment-history.dto.ts
  src/apis/free-post-comments/free-post-comment-history/free-post-comment-history.module.ts
  src/apis/free-post-comments/free-post-comment-history/repositories/free-post-comment-history.repository.ts
  src/apis/free-post-comments/free-post-comment-history/services/free-post-comment-history.service.spec.ts
  src/apis/free-post-comments/free-post-comment-history/services/free-post-comment-history.service.ts
  src/apis/free-post-comments/free-post-comments.module.ts
  src/apis/free-post-comments/services/free-post-comments.service.ts
  src/apis/free-post-reply-comments/free-post-reply-comment-history/dto/create-free-post-reply-comment-history.dto.ts
  src/apis/free-post-reply-comments/free-post-reply-comment-history/free-post-reply-comment-history.module.ts
  src/apis/free-post-reply-comments/free-post-reply-comment-history/repositories/free-post-reply-comment-history.repository.ts
  src/apis/free-post-reply-comments/free-post-reply-comment-history/services/free-post-reply-comment-history.service.spec.ts
  src/apis/free-post-reply-comments/free-post-reply-comment-history/services/free-post-reply-comment-history.service.ts
  src/apis/free-post-reply-comments/free-post-reply-comments.module.ts
  src/apis/free-post-reply-comments/services/free-post-reply-comments.service.ts
  src/apis/free-posts/free-post-history/dto/create-free-post-history.dto.ts
  src/apis/free-posts/free-post-history/free-post-history.module.ts
  src/apis/free-posts/free-post-history/repositories/free-post-history.repository.ts
  src/apis/free-posts/free-post-history/services/free-post-history.service.spec.ts
  src/apis/free-posts/free-post-history/services/free-post-history.service.ts
  src/apis/free-posts/free-posts.module.ts
  src/apis/free-posts/services/free-posts.service.ts
  src/apis/notice-posts/notice-post-history/dto/create-notice-post-history.dto.ts
  src/apis/notice-posts/notice-post-history/notice-posts-history.module.ts
  src/apis/notice-posts/notice-post-history/repositories/notice-post-history.repository.ts
  src/apis/notice-posts/notice-post-history/services/notice-posts-history.service.ts
  src/apis/notice-posts/notice-posts.module.ts
  src/apis/notice-posts/services/notice-posts.service.ts
  src/apis/users/services/users.service.ts
  src/apis/users/user-history/dto/create-user-history.dto.ts
  src/apis/users/user-history/repositories/user-history.repository.ts
  src/apis/users/user-history/services/user-history.service.spec.ts
  src/apis/users/user-history/services/user-history.service.ts
  src/apis/users/user-history/user-history.module.ts
  src/apis/users/users.module.ts
  src/core/type-orm/type-orm-module-options.factory.ts
  src/entities/subscribers/free-post-comment.subscriber.ts
  src/entities/subscribers/free-post-reply-comment.subscriber.ts
  src/entities/subscribers/free-post.subscriber.ts
  src/entities/subscribers/notice-post.subscriber.ts
  src/entities/subscribers/user.subscriber.ts
Labels: Refactor

#139 feat/QYOG-38 modify swagger dto
  src/apis/auth/social/dto/auth-social.dto.ts
Labels: Doc

#141 자유게시글 댓글 대댓글 통합
  migrations/free-post/1708158270600-infinity-nested-comment.ts
  src/apis/api.module.ts
  src/apis/free-post-comments/constants/free-post-comment.constant.ts
  src/apis/free-post-comments/dto/create-free-post-comment.dto.ts
  src/apis/free-post-comments/dto/find-free-post-comment-list-query.dto.ts
  src/apis/free-post-comments/dto/free-post-comment.dto.ts
  src/apis/free-post-comments/dto/free-post-comments-item.dto.ts
  src/apis/free-post-comments/dto/put-update-free-post-comment.dto.ts
  src/apis/free-post-comments/services/free-post-comments.service.ts
  src/apis/free-post-reply-comments/constants/free-post-reply-comment.constant.ts
  src/apis/free-post-reply-comments/constants/free-post-reply-comment.enum.ts
  src/apis/free-post-reply-comments/controllers/free-post-reply-comments.controller.spec.ts
  src/apis/free-post-reply-comments/controllers/free-post-reply-comments.controller.ts
  src/apis/free-post-reply-comments/controllers/free-post-reply-comments.swagger.ts
  src/apis/free-post-reply-comments/dto/create-free-post-reply-comment.dto.ts
  src/apis/free-post-reply-comments/dto/find-free-post-reply-comment-list-query.dto.ts
  src/apis/free-post-reply-comments/dto/free-post-reply-comment.dto.ts
  src/apis/free-post-reply-comments/dto/free-post-reply-comments-item.dto.ts
  src/apis/free-post-reply-comments/dto/put-update-free-post-reply-comment.dto.ts
  src/apis/free-post-reply-comments/free-post-reply-comments.module.ts
  src/apis/free-post-reply-comments/services/free-post-reply-comments.service.spec.ts
  src/apis/free-post-reply-comments/services/free-post-reply-comments.service.ts
  src/apis/free-posts/repositories/free-post-reply-comment.repository.ts
  src/entities/FreePost.ts
  src/entities/FreePostComment.ts
  src/entities/FreePostCommentHistory.ts
  src/entities/FreePostReplyComment.ts
  src/entities/FreePostReplyCommentHistory.ts
  src/entities/FreePostReplyCommentReaction.ts
  src/entities/ReactionType.ts
  src/entities/User.ts
  src/entities/subscribers/free-post-reply-comment.subscriber.ts
  src/helpers/query.helper.ts
Labels: Modify

#143 전공 생성 API admins path로 이동
  src/apis/admins/admins.module.ts
  src/apis/admins/controllers/admins.controller.ts
  src/apis/admins/controllers/admins.swagger.ts
  src/apis/api.module.ts
  src/apis/auth/social/controllers/auth-social.swagger.ts
  src/apis/major/controllers/major.controller.ts
  src/apis/major/controllers/major.swagger.ts
Labels: Refactor

#147 게시글 전체조회 api
  src/apis/api.module.ts
  src/apis/free-post-comments/dto/find-free-post-comment-list-query.dto.ts
  src/apis/free-posts/dto/find-free-post-list-query.dto.ts
  src/apis/notice-posts/dto/find-notice-post-list-query.dto.ts
  src/apis/posts/constants/post.constant.ts
  src/apis/posts/constants/post.enum.ts
  src/apis/posts/controllers/posts.controller.ts
  src/apis/posts/controllers/posts.swagger.ts
  src/apis/posts/dto/find-post-list-query.dto.ts
  src/apis/posts/dto/post.dto.ts
  src/apis/posts/dto/posts-item.dto.ts
  src/apis/posts/posts.module.ts
  src/apis/posts/repositories/post.repository.ts
  src/apis/posts/services/posts.service.ts
  src/dto/transformer/csv-to-order.decorator.ts
Labels: Feat, Fix

#142 공지게시글 댓글 대댓글, reaction API
  migrations/notice-post/1708246489577-infinity-nested-comment.ts
  src/apis/api.module.ts
  src/apis/free-post-comments/services/free-post-comments.service.ts
  src/apis/notice-post-comments/constants/notice-post-comment.constant.ts
  src/apis/notice-post-comments/constants/notice-post-comment.enum.ts
  src/apis/notice-post-comments/controllers/notice-post-comments.controller.ts
  src/apis/notice-post-comments/controllers/notice-post-comments.swagger.ts
  src/apis/notice-post-comments/dto/create-notice-post-comment.dto.ts
  src/apis/notice-post-comments/dto/find-notice-post-comment-list-query.dto.ts
  src/apis/notice-post-comments/dto/notice-post-comment.dto.ts
  src/apis/notice-post-comments/dto/notice-post-comments-item.dto.ts
  src/apis/notice-post-comments/dto/put-update-notice-post-comment.dto.ts
  src/apis/notice-post-comments/notice-post-comments.module.ts
  src/apis/notice-post-comments/repositories/notice-post-comment.repository.ts
  src/apis/notice-post-comments/services/notice-post-comments.service.ts
  src/apis/notice-posts/notice-posts.module.ts
  src/entities/NoticePost.ts
  src/entities/NoticePostComment.ts
  src/entities/NoticePostCommentHistory.ts
  src/entities/NoticePostCommentReaction.ts
  src/entities/NoticePostReplyComment.ts
  src/entities/NoticePostReplyCommentHistory.ts
  src/entities/NoticePostReplyCommentReaction.ts
  src/entities/ReactionType.ts
  src/entities/User.ts
Labels: Feat

#144 operationId 컨트롤러 명이 전부 소문자로 나오는 문제 수정
  src/bootstrap.service.ts
Labels: Modify
