Repository modern-agile-team/dongurami-server-v2, pull requests merged in 2024-03, with the labels that each got.

#149 ValidationError class 이름 및 경로명 수정
  src/apis/admins/controllers/admins.swagger.ts
  src/apis/auth/controllers/auth.swagger.ts
  src/apis/auth/social/controllers/auth-social.swagger.ts
  src/apis/dev/controllers/dev.swagger.ts
  src/apis/free-post-comments/controllers/free-post-comments.swagger.ts
  src/apis/free-posts/controllers/free-posts.swagger.ts
  src/apis/notice-post-comments/controllers/notice-post-comments.swagger.ts
  src/apis/notice-posts/controllers/notice-posts.swagger.ts
  src/apis/posts/controllers/posts.swagger.ts
  src/apis/users/controllers/users.swagger.ts
  src/types/custom-validation-errors.type.ts
Labels: Refactor

#148 파일 업로드 api
  .github/workflows/dongurami-v2.yml
  dockerfile
  migrations/attachment/1709025647217-create-attachment-table.ts
  package-lock.json
  package.json
  src/apis/api.module.ts
  src/apis/attachments/attachments.module.ts
  src/apis/attachments/constants/file.constant.ts
  src/apis/attachments/controllers/attachments.controller.ts
  src/apis/attachments/controllers/attachments.swagger.ts
  src/apis/attachments/dto/attachment.dto.ts
  src/apis/attachments/dto/create-attachment.dto.ts
  src/apis/attachments/dto/file-upload.dto.ts
  src/apis/attachments/repositories/attachment.repository.ts
  src/apis/attachments/services/attachments.service.ts
  src/apis/free-post-comments/constants/free-post-comment.constant.ts
  src/bootstrap.service.ts
  src/core/app-config/app-config.module.ts
  src/core/app-config/constants/app-config.constant.ts
  src/entities/Attachment.ts
  src/entities/User.ts
  src/pipes/constants/rewrite-validation-options.token.ts
  src/pipes/custom-validation.pipe.ts
  src/pipes/decorators/rewrite-validation-options.decorator.ts
  src/s3/constants/s3-client.token.ts
  src/s3/s3.module.ts
  src/s3/services/s3.service.ts
Labels: Feat

#150 File upload api 스웨거 400 Error schema 수정
  src/apis/attachments/controllers/attachments.swagger.ts
Labels: Doc

#151 Delete useless code
  src/app.module.ts
Labels: Delete

#152 동아리 리스트 조회 API
  migrations/club/1708774714811-club.ts
  migrations/club/1708776176949-club-history.ts
  migrations/club/1708776486100-club-tag.ts
  migrations/club/1708777940870-club-tag-link.ts
  migrations/club/1708778638574-club-category.ts
  migrations/club/1708779125344-club-category-link.ts
  migrations/club/1710570954727-temp-club-seed.ts
  src/apis/api.module.ts
  src/apis/club-categories/dto/club-category.dto.ts
  src/apis/club-categories/repositories/club-category.repository.ts
  src/apis/club-category-links/club-category-links.module.ts
  src/apis/club-category-links/repositories/club-category-link.repository.ts
  src/apis/club-tag-links/club-tag-links.module.ts
  src/apis/club-tag-links/repositories/club-tag-link.repository.ts
  src/apis/club-tags/dto/club-tag.dto.ts
  src/apis/club-tags/repositories/club-tag.repository.ts
  src/apis/clubs/clubs.module.ts
  src/apis/clubs/constants/club.constant.ts
  src/apis/clubs/constants/club.enum.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/dto/club.dto.ts
  src/apis/clubs/dto/clubs-item.dto.ts
  src/apis/clubs/dto/find-club-list-query.dto.ts
  src/apis/clubs/repositories/club.repository.ts
  src/apis/clubs/services/clubs.service.ts
  src/entities/Club.ts
  src/entities/ClubCategory.ts
  src/entities/ClubCategoryLink.ts
  src/entities/ClubHistory.ts
  src/entities/ClubTag.ts
  src/entities/ClubTagLink.ts
  src/entities/User.ts
Labels: Feat, DB

#153 게시글 태그 생성 API
  migrations/free-post/1710580167472-free-post-tag-link.ts
  migrations/notice-post/1710581054906-notice-post-tag-link.ts
  migrations/post-tag/1710579847510-post-tag.ts
  src/apis/api.module.ts
  src/apis/free-posts/controllers/free-posts.swagger.ts
  src/apis/post-tags/constants/post-tag.constant.ts
  src/apis/post-tags/controllers/post-tags.controller.ts
  src/apis/post-tags/controllers/post-tags.swagger.ts
  src/apis/post-tags/dto/create-post-tag.dto.ts
  src/apis/post-tags/dto/post-tag.dto.ts
  src/apis/post-tags/post-tags.module.ts
  src/apis/post-tags/repositories/post-tag.repository.ts
  src/apis/post-tags/services/post-tags.service.ts
  src/constants/error/error-code.constant.ts
  src/entities/FreePost.ts
  src/entities/FreePostTagLink.ts
  src/entities/NoticePost.ts
  src/entities/NoticePostTagLink.ts
  src/entities/PostTag.ts
  src/entities/User.ts
Labels: Feat, DB

#157 modify club_category table
  migrations/club/1711623491465-updated-at-column-club-category.ts
  src/entities/ClubCategory.ts
Labels: DB

#154 게시글, 댓글 전체조회에 응답에 user 정보 추가
  src/apis/free-post-comments/dto/free-post-comments-item.dto.ts
  src/apis/free-post-comments/services/free-post-comments.service.ts
  src/apis/free-posts/dto/free-posts-item.dto.ts
  src/apis/free-posts/services/free-posts.service.ts
  src/apis/notice-post-comments/dto/notice-post-comments-item.dto.ts
  src/apis/notice-post-comments/services/notice-post-comments.service.ts
  src/apis/notice-posts/dto/notice-posts-item.dto.ts
  src/apis/notice-posts/services/notice-posts.service.ts
  src/apis/posts/dto/post.dto.ts
  src/apis/posts/dto/posts-item.dto.ts
  src/apis/posts/repositories/post.repository.ts
  src/helpers/query.helper.ts
Labels: Feat
