Repository modern-agile-team/dongurami-server-v2, pull requests merged in 2024-04, with the labels that each got.

#156 동아리 생성 api
  src/apis/admins/admins.module.ts
  src/apis/admins/controllers/admins.controller.ts
  src/apis/admins/controllers/admins.swagger.ts
  src/apis/api.module.ts
  src/apis/club-categories/club-categories.module.ts
  src/apis/club-tags/club-tags.module.ts
  src/apis/club-tags/constants/club-tag.constant.ts
  src/apis/club-tags/dto/create-club-tag.dto.ts
  src/apis/club-tags/services/club-tags.service.ts
  src/apis/clubs/clubs.module.ts
  src/apis/clubs/constants/club.constant.ts
  src/apis/clubs/dto/club-with-category-and-tag.dto.ts
  src/apis/clubs/dto/club.dto.ts
  src/apis/clubs/dto/create-club-category-link.dto.ts
  src/apis/clubs/dto/create-club-request-body.dto.ts
  src/apis/clubs/dto/create-club-tag-link.dto.ts
  src/apis/clubs/services/clubs.service.ts
  src/bootstrap.service.ts
  src/entities/subscribers/club.subscriber.ts
  src/http-exceptions/exceptions/http-unprocessable-entity.exception.ts
  src/http-exceptions/filters/http-unprocessable-exception.filter.ts
  src/http-exceptions/http-exception.module.ts
Labels: Feat

#161 자유게시글 수정 시 태그를 갱신함
  src/apis/free-posts/controllers/free-posts.controller.spec.ts
  src/apis/free-posts/controllers/free-posts.controller.ts
  src/apis/free-posts/dto/patch-update-free-post.dto.ts
  src/apis/free-posts/dto/put-update-free-post.dto.ts
  src/apis/free-posts/services/free-posts.service.spec.ts
  src/apis/free-posts/services/free-posts.service.ts
Labels: Feat

#162 공지게시글 수정 시 태그를 갱신함
  src/apis/notice-posts/dto/patch-update-notice-post.dto.ts
  src/apis/notice-posts/dto/put-update-notice-post.dto.ts
  src/apis/notice-posts/services/notice-posts.service.ts
Labels: Feat

#165 공지게시글 리액션 생성 삭제 API
  src/apis/notice-posts/controllers/notice-posts.controller.ts
  src/apis/notice-posts/controllers/notice-posts.swagger.ts
  src/apis/notice-posts/notice-posts.module.ts
  src/apis/notice-posts/services/notice-posts.service.ts
Labels: Feat

#158 Create club category api
  src/apis/admins/admins.module.ts
  src/apis/admins/controllers/admins.controller.ts
  src/apis/admins/controllers/admins.swagger.ts
  src/apis/club-categories/club-categories.module.ts
  src/apis/club-categories/constants/club-category.constant.ts
  src/apis/club-categories/dto/club-category.dto.ts
  src/apis/club-categories/dto/create-club-category-request-body.dto.ts
  src/apis/club-categories/services/club-categories.service.ts
  src/constants/error/club-category/club-category-error-code.constant.ts
  src/constants/error/club-category/club-category-error-message.constant.ts
  src/constants/error/error-code.constant.ts
  src/constants/error/error-message.constant.ts
Labels: Feat

#163 공지게시글 상세 조회 시 응답에 태그를 추가함
  src/apis/notice-post-comments/services/notice-post-comments.service.ts
  src/apis/notice-posts/services/notice-posts.service.ts
Labels: Feat

#164 자유게시글 상세 조회 시 응답에 태그를 추가함
  src/apis/free-post-comments/services/free-post-comments.service.ts
  src/apis/free-posts/services/free-posts.service.ts
Labels: Feat

#166 동아리 지원서 폼 마이그레이션
  migrations/club/1711789044196-club-applications-form.ts
  migrations/club/1711791453308-club-applications-form-history.ts
  src/entities/Club.ts
  src/entities/ClubApplicationsForm.ts
  src/entities/ClubApplicationsFormHistory.ts
Labels: DB

#167 동아리 태그 추가 API
  src/apis/club-tags/dto/club-tag.dto.ts
  src/apis/club-tags/services/club-tags.service.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/dto/bulk-append-club-tag.dto.ts
  src/apis/clubs/dto/create-club-tag-link.dto.ts
  src/apis/clubs/services/clubs.service.ts
Labels: Feat

#168 동아리 태그 리스트 조회 API
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/services/clubs.service.ts
Labels: Feat

#170 동아리 상세 조회 API
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
Labels: Feat

#169 동아리 태그 제거 API
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/services/clubs.service.ts
  src/pipes/parse-separable-positive-int.pipe.ts
Labels: Feat

#172 동아리 구성원 리스트 조회 API
  migrations/club/1712482591735-club-member.ts
  src/apis/api.module.ts
  src/apis/club-members/club-members.module.ts
  src/apis/club-members/dto/club-member-item.dto.ts
  src/apis/club-members/dto/club-member.dto.ts
  src/apis/club-members/repositories/club-member.repository.ts
  src/apis/club-members/services/club-members.service.ts
  src/apis/clubs/clubs.module.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/services/clubs.service.ts
  src/entities/Club.ts
  src/entities/ClubMember.ts
  src/entities/User.ts
Labels: Feat, DB

#175 모든 동아리 카테고리 전체 조회 API
  src/apis/club-categories/club-categories.module.ts
  src/apis/club-categories/constants/club-category.constant.ts
  src/apis/club-categories/controllers/club-categories.controller.ts
  src/apis/club-categories/controllers/club-categories.swagger.ts
  src/apis/club-categories/dto/find-club-category-list-query.dto.ts
  src/apis/club-categories/services/club-categories.service.ts
Labels: Feat

#173 동아리 생성 시 동아리 지원서 폼 생성 추가
  migrations/club/1712799626196-change-club-application-form-table-name.ts
  src/apis/api.module.ts
  src/apis/club-application-form/club-application-form.module.ts
  src/apis/club-application-form/constants/club-application-form.enum.ts
  src/apis/club-application-form/dto/club-application-form-question-item.dto.ts
  src/apis/club-application-form/dto/club-application-form.dto.ts
  src/apis/club-application-form/dto/create-club-application-form.dto.ts
  src/apis/club-application-form/repositories/club-application-form.repository.ts
  src/apis/club-application-form/services/club-application-form.service.ts
  src/apis/club-application-form/types/club-application-form.type.ts
  src/apis/clubs/clubs.module.ts
  src/apis/clubs/services/clubs.service.ts
  src/entities/Club.ts
  src/entities/ClubApplicationForm.ts
  src/entities/ClubApplicationFormHistory.ts
  src/entities/subscribers/club-application-form.subscriber.ts
Labels: Feat

#174 최신 동아리 지원서 폼 조회 API
  src/apis/club-application-form/services/club-application-form.service.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/services/clubs.service.ts
Labels: Feat

#176 동아리 게시글 생성 API
  migrations/club/1712839843648-club-post.ts
  migrations/club/1712842023402-club-post-history.ts
  src/apis/api.module.ts
  src/apis/club-members/services/club-members.service.ts
  src/apis/club-posts/club-posts.module.ts
  src/apis/club-posts/constants/club-post.constant.ts
  src/apis/club-posts/constants/club-post.enum.ts
  src/apis/club-posts/dto/club-post.dto.ts
  src/apis/club-posts/repositories/club-post.repository.ts
  src/apis/club-posts/services/club-posts.service.ts
  src/apis/clubs/clubs.module.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/dto/create-club-post-request-body.dto.ts
  src/apis/clubs/services/clubs.service.ts
  src/entities/Club.ts
  src/entities/ClubPost.ts
  src/entities/ClubPostHistory.ts
  src/entities/User.ts
  src/entities/subscribers/club-post.subscriber.ts
Labels: Feat, DB

#178 동아리 구성원 역할 enum 추가
  src/apis/club-members/constants/club-member.enum.ts
  src/apis/club-members/dto/club-member.dto.ts
  src/entities/ClubMember.ts
Labels: Refactor

#177 동아리 지원서 폼 수정 API
  migrations/club/1712989702178-club-applications-form-add-user-id.ts
  src/apis/club-application-form/dto/club-application-form-question-item.dto.ts
  src/apis/club-application-form/dto/create-club-application-form.dto.ts
  src/apis/club-application-form/dto/put-update-club-application-form.dto.ts
  src/apis/club-application-form/services/club-application-form.service.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/services/clubs.service.ts
  src/decorators/validators/is-after.decorator.ts
  src/decorators/validators/is-before.decorator.ts
  src/decorators/validators/validate-by-class.decorator.ts
  src/entities/ClubApplicationForm.ts
  src/entities/User.ts
  src/entities/subscribers/club-application-form.subscriber.ts
Labels: Feat, Fix, DB

#181 공지게시글 태그 관리 이중화
  migrations/notice/1713082909950-notice-post-add-tags.ts
  src/apis/notice-posts/dto/notice-post.dto.ts
  src/apis/notice-posts/services/notice-posts.service.ts
  src/entities/NoticePost.ts
  src/entities/NoticePostHistory.ts
Labels: Feat

#179 동아리 태그 관리 이중화
  migrations/club/1712996267068-club-add-tags.ts
  src/apis/clubs/dto/club.dto.ts
  src/apis/clubs/dto/clubs-item.dto.ts
  src/apis/clubs/services/clubs.service.ts
  src/entities/Club.ts
  src/entities/ClubHistory.ts
Labels: Refactor, Modify

#182 동아리 게시글 태그 관리 이중화
  migrations/__utils/util.ts
  migrations/club/1713162804915-club-post-tag-link.ts
  src/apis/club-post-tag-links/repositories/club-post-tag-link.repository.ts
  src/apis/club-posts/constants/club-post.constant.ts
  src/apis/club-posts/dto/club-post.dto.ts
  src/apis/club-posts/dto/create-club-post.dto.ts
  src/apis/club-posts/services/club-posts.service.ts
  src/apis/clubs/clubs.module.ts
  src/apis/clubs/dto/create-club-post-request-body.dto.ts
  src/apis/clubs/dto/create-club-post-tag-link.dto.ts
  src/apis/clubs/services/clubs.service.ts
  src/entities/ClubPost.ts
  src/entities/ClubPostHistory.ts
  src/entities/ClubPostTagLink.ts
  src/entities/PostTag.ts
  src/entities/User.ts
Labels: Feat

#185 Bulk create club post tag links 로직 bug 수정
  src/apis/clubs/services/clubs.service.ts
Labels: Fix

#184 동아리 후기 생성 API
  migrations/club/1713268413997-club-review.ts
  migrations/club/1713332089454-club-review-history.ts
  src/apis/club-reviews/club-reviews.module.ts
  src/apis/club-reviews/constants/club-review.constant.ts
  src/apis/club-reviews/constants/club-review.enum.ts
  src/apis/club-reviews/dto/club-review.dto.ts
  src/apis/club-reviews/dto/create-club-review.dto.ts
  src/apis/club-reviews/repositories/club-review.repository.ts
  src/apis/club-reviews/services/club-reviews.service.ts
  src/apis/clubs/clubs.module.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/dto/create-club-review-request-body.dto.ts
  src/apis/clubs/services/clubs.service.ts
  src/constants/error/club-review/club-review-error-code.constant.ts
  src/constants/error/club-review/club-review-error-message.constant.ts
  src/constants/error/error-code.constant.ts
  src/constants/error/error-message.constant.ts
  src/entities/Club.ts
  src/entities/ClubReview.ts
  src/entities/ClubReviewHistory.ts
  src/entities/User.ts
  src/entities/subscribers/club-review.subscriber.ts
Labels: Feat

#186 CreateClubReview swagger 문서 생성 메서드 에러 수정
  src/apis/clubs/controllers/clubs.swagger.ts
Labels: Fix

#187 build/deploy-notify-slack job에 if: always() 조건 추가
  .github/workflows/dongurami-v2.yml
Labels: Deploy

#189 게시글 댓글 조회 시 버그 수정
  src/apis/free-post-comments/services/free-post-comments.service.ts
  src/apis/notice-post-comments/services/notice-post-comments.service.ts
Labels: Fix

#190 공지 게시글 댓글 작성 시 게시글의 댓글 허용 여부 체크 로직 추가
  src/apis/notice-post-comments/controllers/notice-post-comments.swagger.ts
  src/apis/notice-post-comments/services/notice-post-comments.service.ts
  src/constants/error/error-code.constant.ts
  src/constants/error/error-message.constant.ts
  src/constants/error/notice-post-comment/notice-post-comment-error-code.constant.ts
  src/constants/error/notice-post-comment/notice-post-comment-error-message.constant.ts
Labels: Feat

#191 Attachment 테이블 path 컬럼 사이즈 수정
  migrations/attachment/1713955105509-modify-attachment-path-length.ts
  src/entities/Attachment.ts
Labels: DB

#188 게시글 전체조회 버그 수정
  src/apis/posts/repositories/post.repository.ts
Labels: Fix

#192 동아리 게시글 생성 시 파일 업로드 추가
  migrations/club/1713956277322-club-post-attachment.ts
  src/apis/attachments/attachments.module.ts
  src/apis/attachments/dto/attachment.dto.ts
  src/apis/attachments/services/attachments.service.ts
  src/apis/club-post-attachments/club-post-attachments.module.ts
  src/apis/club-post-attachments/constants/club-post-attachment.constant.ts
  src/apis/club-post-attachments/dto/create-club-post-attachment.dto.ts
  src/apis/club-post-attachments/repositories/club-post-attachment.repository.ts
  src/apis/club-post-attachments/services/club-post-attachments.service.ts
  src/apis/club-posts/club-posts.module.ts
  src/apis/club-posts/dto/club-post.dto.ts
  src/apis/club-posts/dto/create-club-post.dto.ts
  src/apis/club-posts/services/club-posts.service.ts
  src/apis/clubs/clubs.module.ts
  src/apis/clubs/dto/create-club-post-request-body.dto.ts
  src/apis/clubs/services/clubs.service.ts
  src/entities/Attachment.ts
  src/entities/ClubPost.ts
  src/entities/ClubPostAttachment.ts
Labels: Feat, DB
