Repository modern-agile-team/dongurami-server-v2, pull requests merged in 2024-05, with the labels that each got.

#194 ReactionType Enum 이름 수정
  src/apis/reactions/constants/reaction.enum.ts
  src/apis/reactions/dto/create-reaction.dto.ts
  src/apis/reactions/dto/remove-reaction.dto.ts
  src/apis/reactions/services/reactions.service.ts
Labels: Refactor

#195 특정 자유 게시글 reactions 전체 조회 API
  src/apis/free-posts/constants/free-post.constant.ts
  src/apis/free-posts/controllers/free-posts.controller.ts
  src/apis/free-posts/controllers/free-posts.swagger.ts
  src/apis/free-posts/dto/find-free-post-reactions-list-query.dto.ts
  src/apis/free-posts/dto/free-post-reaction.dto.ts
  src/apis/free-posts/dto/free-post-reactions-item.dto.ts
  src/apis/free-posts/services/free-posts.service.ts
  src/apis/reactions/services/reactions.service.ts
  src/apis/reactions/types/reaction.type.ts
  src/types/type.ts
Labels: Feat

#193 동아리 지원서 API
  migrations/club/1713083761184-club-application.ts
  migrations/club/1713084768625-club-application_history.ts
  package-lock.json
  package.json
  src/apis/api.module.ts
  src/apis/club-application-form/dto/club-application-form-question-item.dto.ts
  src/apis/club-application-form/dto/create-club-application-form.dto.ts
  src/apis/club-application-form/dto/put-update-club-application-form.dto.ts
  src/apis/club-application-form/services/club-application-form.service.ts
  src/apis/club-application-form/types/club-application-form.type.ts
  src/apis/club-applications/club-applications.module.ts
  src/apis/club-applications/constants/club-application.constant.ts
  src/apis/club-applications/constants/club-application.enum.ts
  src/apis/club-applications/dto/club-application-answer-item.dto.ts
  src/apis/club-applications/dto/club-application-answers-item-request.dto.ts
  src/apis/club-applications/dto/club-application.dto.ts
  src/apis/club-applications/dto/club-applications-item.dto.ts
  src/apis/club-applications/dto/create-club-application.dto.ts
  src/apis/club-applications/dto/find-club-application-list-query.dto.ts
  src/apis/club-applications/dto/patch-update-club-application.dto.ts
  src/apis/club-applications/dto/update-club-application-status.dto.ts
  src/apis/club-applications/repositories/club-application.repository.ts
  src/apis/club-applications/services/club-applications.service.ts
  src/apis/club-members/services/club-members.service.ts
  src/apis/clubs/clubs.module.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/dto/create-club-application-request-body.dto.ts
  src/apis/clubs/dto/find-club-application-list-request-query.dto.ts
  src/apis/clubs/services/clubs.service.ts
  src/constants/error/club-application/club-application-error-code.constant.ts
  src/constants/error/club-application/club-application-error-message.constant.ts
  src/constants/error/club-member/club-member-error-code.constant.ts
  src/constants/error/club-member/club-member-error-message.constant.ts
  src/constants/error/error-code.constant.ts
  src/constants/error/error-message.constant.ts
  src/entities/Club.ts
  src/entities/ClubApplication.ts
  src/entities/ClubApplicationForm.ts
  src/entities/ClubApplicationHistory.ts
  src/entities/User.ts
  src/entities/subscribers/club-application.subscriber.ts
Labels: Feat

#196 공지게시글 리액션 페이지네이션 조회
  src/apis/free-posts/controllers/free-posts.controller.ts
  src/apis/notice-posts/constants/notice-post.constant.ts
  src/apis/notice-posts/controllers/notice-posts.controller.ts
  src/apis/notice-posts/controllers/notice-posts.swagger.ts
  src/apis/notice-posts/dto/find-notice-post-reactions-list-query.dto.ts
  src/apis/notice-posts/dto/notice-post-reaction.dto.ts
  src/apis/notice-posts/dto/notice-post-reactions-item.dto.ts
  src/apis/notice-posts/services/notice-posts.service.ts
Labels: Feat

#197 동아리 후기 reaction 생성, 삭제 API
  migrations/club/1715756445187-club-review-reaction.ts
  src/apis/club-reviews/services/club-reviews.service.ts
  src/apis/clubs/clubs.module.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/services/clubs.service.ts
  src/entities/ClubReview.ts
  src/entities/ClubReviewReaction.ts
  src/entities/ReactionType.ts
  src/entities/User.ts
Labels: Feat, DB

#198 특정 동아리 후기 Pagination 및 평균 별점 조회 API
  src/apis/club-reviews/club-reviews.module.ts
  src/apis/club-reviews/constants/club-review.constant.ts
  src/apis/club-reviews/dto/club-reviews-item.dto.ts
  src/apis/club-reviews/dto/find-club-review-list-query.dto.ts
  src/apis/club-reviews/services/club-reviews.service.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/dto/find-club-review-list-request-query.dto.ts
  src/apis/clubs/services/clubs.service.ts
Labels: Feat

#199 공지게시글 단일 응답에 user prop 추가
  src/apis/notice-posts/dto/notice-post.dto.ts
  src/apis/notice-posts/notice-posts.module.ts
  src/apis/notice-posts/services/notice-posts.service.ts
Labels: Feat

#200 자유게시글 응답에 유저 정보 추가 및 익명처리
  src/apis/free-posts/controllers/free-posts.controller.ts
  src/apis/free-posts/dto/free-post.dto.ts
  src/apis/free-posts/dto/free-posts-item.dto.ts
  src/apis/free-posts/free-posts.module.ts
  src/apis/free-posts/services/free-posts.service.ts
  src/common/common.ts
Labels: Feat

#201 특정 동아리에 대한 리뷰 별점 개수 및 평점 조회 API
  src/apis/club-reviews/dto/score.dto.ts
  src/apis/club-reviews/services/club-reviews.service.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/services/clubs.service.ts
Labels: Feat

#203 특정 동아리 게시글 reaction 생성 / 제거 API
  migrations/club/1716101991787-club-post-reaction.ts
  src/apis/club-posts/club-posts.module.ts
  src/apis/club-posts/dto/club-post.dto.ts
  src/apis/club-posts/services/club-posts.service.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/services/clubs.service.ts
  src/entities/ClubPost.ts
  src/entities/ClubPostReaction.ts
  src/entities/ReactionType.ts
  src/entities/User.ts
Labels: Feat, DB

#204 동아리 게시글 댓글 생성 API
  migrations/club/1716106149540-club-post-comment.ts
  migrations/club/1716106530548-club-post-comment-history.ts
  src/apis/api.module.ts
  src/apis/club-post-comments/club-post-comments.module.ts
  src/apis/club-post-comments/constants/club-post-comment.constant.ts
  src/apis/club-post-comments/constants/club-post-comment.enum.ts
  src/apis/club-post-comments/dto/club-post-comment.dto.ts
  src/apis/club-post-comments/repositories/club-post-comment.repository.ts
  src/apis/club-post-comments/services/club-post-comments.service.ts
  src/apis/club-posts/dto/club-post.dto.ts
  src/apis/clubs/clubs.module.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/dto/create-club-post-comment-request-body.dto.ts
  src/apis/clubs/services/clubs.service.ts
  src/entities/ClubPost.ts
  src/entities/ClubPostComment.ts
  src/entities/ClubPostCommentHistory.ts
  src/entities/User.ts
  src/entities/subscribers/club-post-comment.subscriber.ts
Labels: Feat, DB

#205 swagger 동아리 지원서 리스트 -> 동아리 지원내역 리스트로 표기 변경
  src/apis/clubs/controllers/clubs.controller.ts
Labels: Doc
