Repository modern-agile-team/dongurami-server-v2, pull requests merged in 2024-06, with the labels that each got.

#207 지원서 기간 필드 nullable 명시
  src/apis/club-application-form/dto/club-application-form.dto.ts
Labels: Refactor

#210 동아리 게시글 삭제 API
  src/apis/club-posts/services/club-posts.service.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/services/clubs.service.ts
Labels: Feat

#211 동아리 게시글 댓글 Pagination 조회 API
  src/apis/club-post-comments/dto/find-and-count-club-post-comments.dto.ts
  src/apis/club-post-comments/services/club-post-comments.service.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/dto/find-club-post-comments-list-request-query.dto.ts
  src/apis/clubs/services/clubs.service.ts
Labels: Feat

#212 동아리 게시글 댓글 수정 삭제 API
  src/apis/club-post-comments/dto/club-post-comment.dto.ts
  src/apis/club-post-comments/dto/patch-update-club-post-comment.dto.ts
  src/apis/club-post-comments/dto/remove-club-post-comment.dto.ts
  src/apis/club-post-comments/services/club-post-comments.service.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/dto/patch-update-club-post-comment-request-body.dto.ts
  src/apis/clubs/services/clubs.service.ts
  src/entities/subscribers/club-post-comment.subscriber.ts
Labels: Feat

#208 동아리 리뷰 수정 삭제 API
  src/apis/club-reviews/dto/patch-update-club-review.dto.ts
  src/apis/club-reviews/dto/remove-club-review.dto.ts
  src/apis/club-reviews/services/club-reviews.service.ts
  src/apis/clubs/controllers/clubs.controller.ts
  src/apis/clubs/controllers/clubs.swagger.ts
  src/apis/clubs/dto/patch-update-club-review-request.dto.ts
  src/apis/clubs/services/clubs.service.ts
  src/apis/dev/controllers/dev.swagger.ts
  src/apis/free-post-comments/controllers/free-post-comments.swagger.ts
  src/entities/subscribers/club-review.subscriber.ts
Labels: Feat

#213 통과 하지 못하는 테스트 코드들 삭제
  src/apis/auth/controllers/auth.controller.spec.ts
  src/apis/auth/services/auth.service.spec.ts
  src/apis/common-posts/services/common-posts.service.spec.ts
  src/apis/free-post-comments/controllers/free-post-comments.controller.spec.ts
  src/apis/free-post-comments/services/free-post-comments.service.spec.ts
  src/apis/free-posts/controllers/free-posts.controller.spec.ts
  src/apis/free-posts/services/free-posts.service.spec.ts
  src/apis/reactions/services/reactions.service.spec.ts
  src/apis/users/controllers/users.controller.spec.ts
  src/apis/users/services/users.service.spec.ts
  src/dto/transformer/csv-to-order.decorator.spec.ts
  src/libs/encryption/services/encryption.service.spec.ts
Labels: Delete
