Repository modern-agile-team/dongurami-server-v2, pull requests merged in 2024-01, with the labels that each got.

#111 Feat/#109/user find one
  src/apis/users/controllers/users.controller.ts
  src/apis/users/controllers/users.swagger.ts
  src/apis/users/services/users.service.ts
Labels: Feat

#114 major code refactoring
  src/apis/major/controllers/major.controller.ts
  src/apis/major/controllers/major.swagger.ts
  src/apis/major/major.module.ts
  src/apis/major/services/major.service.ts
  src/apis/users/services/users.service.ts
  src/apis/users/users.module.ts
Labels: Refactor

#117 user put update api
  src/apis/notice-posts/services/notice-posts.service.ts
  src/apis/users/controllers/users.controller.ts
  src/apis/users/controllers/users.swagger.ts
  src/apis/users/dto/put-update-user.dto.ts
  src/apis/users/services/users.service.ts
Labels: Feat

#120 Social signup / signin
  migrations/1704208353171-add-modify-user-table-column.ts
  migrations/1704441168745-add-enum-type-in-loginType.ts
  package-lock.json
  package.json
  src/apis/api.module.ts
  src/apis/auth/auth.module.ts
  src/apis/auth/social/auth-social.module.ts
  src/apis/auth/social/controllers/auth-social.controller.ts
  src/apis/auth/social/controllers/auth-social.swagger.ts
  src/apis/auth/social/dto/auth-registration.dto.ts
  src/apis/auth/social/dto/auth-social.dto.ts
  src/apis/auth/social/service/auth-registration.service.ts
  src/apis/auth/social/service/auth-social.service.ts
  src/apis/auth/social/types/auth-social.type.ts
  src/apis/auth/util/getSnsProfile.ts
  src/apis/users/constants/user.enum.ts
  src/apis/users/dto/create-user-request-body.dto.ts
  src/apis/users/dto/user.dto.ts
  src/apis/users/services/users.service.ts
  src/entities/User.ts
Labels: Feat

#124 문서상 오창훈 추가
  .github/CODEOWNERS
  README.md
  package.json
Labels: Doc, Auto

#121 문서관리를 지라로 하기 위한 작업
  .github/.COMMIT_TEMPLATE.txt
  .github/labels.json
  .github/pull_request_template.md
  README.md
  docs/guides/BRANCH_STRATEGY.md
  docs/guides/COMMIT_CONVENTION.md
  docs/guides/DB_MIGRATION.md
  docs/guides/GITHUB_LABELS.md
  scripts/prepare-commit-msg.sh
Labels: Doc, Auto

#126 swagger tag 분리 및 단수형 표기
  src/apis/free-post-comments/controllers/free-post-comments.controller.ts
  src/apis/free-post-reply-comments/controllers/free-post-reply-comments.controller.ts
  src/apis/free-posts/controllers/free-posts.controller.ts
  src/apis/major/controllers/major.controller.ts
  src/apis/notice-posts/controllers/notice-posts.controller.ts
  src/apis/users/controllers/users.controller.ts
Labels: Doc

#127 error code swagger 스키마로 선언
  src/apis/root/controllers/root.swagger.ts
  src/apis/root/dto/error-code-response.dto.ts
  src/apis/root/services/root.service.ts
Labels: Doc
